FORMAT: 1A
HOST: http://localhost:8080

# diff-api

This API provides HTTP endpoints that accepts JSON base64 encoded binary data on both.

## List all Messages [/]

### List all messages created [GET]

+ Response 200 (application/json)

    {
        "data": [
            {
                "id": 1,
                "leftData": "TWFyaWFuYQ==",
                "rightData": "TWFyaWFuYQ=="
            },
            {
                "id": 3,
                "leftData": "QmFuYW5h",
                "rightData": "TWHDp8Oj"
            },
            {
                "id": 2,
                "leftData": "Q2VsdWxhcg==",
                "rightData": "VGFibGV0cw=="
            },
            {
                "id": 4,
                "leftData": "QmFuYW5h",
                "rightData": "TWFuYW5h"
            },
            {
                "id": 5,
                "leftData": "UGVyYQ==",
                "rightData": "TGFyYW5qYQ=="
            },
            {
                "id": 6,
                "leftData": "THVjYXM=",
                "rightData": null
            },
            {
                "id": 7,
                "leftData": "RGFuaQ==",
                "rightData": "RGFuaQ=="
            }
        ],
        "errors": []
    }

## Create a message on the left endpoint [/v1/diff/1/left]

### Create a message on the left endpoint [POST]

+ Request (application/json)

        {
            "leftData": "Test"
        }

+ Response 200 (text/plain)

    + Body

        {
            "data": [
                {
                    "id": 1,
                    "leftData": "TWFyaWFuYQ==",
                    "rightData": null
                }
            ],
            "errors": []
        }
            
+ Response 500

## Create a message on the right endpoint [/v1/diff/1/right]

### Create a message on the right endpoint [POST]

+ Request (application/json)

        {
            "rightData": "Test"
        }

+ Response 200 (application/json)

    + Body

    {
        "data": [
            {
                "id": 2,
                "leftData": null,
                "rightData": "TWFyaWFuYQ=="
            }
        ],
        "errors": []
    }
            
+ Response 500

## Diff-ed endpoint [/v1/diff/1]

### Diff-ed messages between endpoints [GET]

+ Response 200 (application/json)

    + Body

    {
        "data": {
            "id": 1,
            "result": "EQUAL",
            "message": {
                "id": 1,
                "leftData": "TWFyaWFuYQ==",
                "rightData": "TWFyaWFuYQ=="
            },
            "diff": null
        },
        "errors": []
    }
            
+ Response 500